nflfastr2010 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2010.rds?raw=true'))
nflfastr2011 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2011.rds?raw=true'))
nflfastr2012 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2012.rds?raw=true'))
nflfastr2013 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2013.rds?raw=true'))
nflfastr2014 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2014.rds?raw=true'))
nflfastr2015 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2015.rds?raw=true'))
nflfastr2016 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2016.rds?raw=true'))
nflfastr2017 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2017.rds?raw=true'))
nflfastr2018 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2018.rds?raw=true'))
nflfastr2019 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2019.rds?raw=true'))
nflfastr2020 = readRDS(url('https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_2020.rds?raw=true'))
nflfastRall = rbind(nflfastr2010, nflfastr2011)
nflfastRall = rbind(nflfastRall, nflfastr2012)
nflfastRall = rbind(nflfastRall, nflfastr2013)
nflfastRall = rbind(nflfastRall, nflfastr2014)
nflfastRall = rbind(nflfastRall, nflfastr2015)
nflfastRall = rbind(nflfastRall, nflfastr2016)
nflfastRall = rbind(nflfastRall, nflfastr2017)
nflfastRall = rbind(nflfastRall, nflfastr2018)
nflfastRall = rbind(nflfastRall, nflfastr2019)
nflfastRall = rbind(nflfastRall, nflfastr2020)

saveRDS(nflfastRall, "../../data/nflfastRall.rds")
